server:
  port: 8888

logging:
  level:
    com.zhou.bms2.mapper.*: debug

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    username: root
#    password: 123456
#    url: jdbc:p6spy:mysql://localhost:3306/bms?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/bms?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true
      initial-size: 5
      # 最小空闲连接数 默认：0
      min-idle: 5
      # 最大连接数  默认：8
      max-active: 20
      # 获取连接等待超时的时间(毫秒) 默认：-1
      max-wait: 60000
      # 查询超时时间(秒)
      query-timeout: 2400
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 申请连接时检测连接可用性 默认：false
      test-on-borrow: false
      # 归还连接检测 默认：false
      test-on-return: false
      # 超时是否检测连接可用性
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 (毫秒)
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间(毫秒，默认30分钟)
      min-evictable-idle-time-millis: 300000
      # 通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat；日志用的filter:log4j；防御sql注入的filter:wall
      filters: stat,wall,slf4j
      # 是否缓存PreparedStatement. PSCache对支持游标的数据库性能提升巨大，比如说oracle.在mysql下建议关闭.
      pool-prepared-statements: false
      # 每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 50
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql(Sql合并)功能；慢SQL记录(配置超过5秒就是慢，默认是3秒)
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-max-count: 1000
        session-stat-enable: true
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: root
        login-password: root
        allow: 127.0.0.1
        reset-enable: true
      filter:
        stat:
          enabled: true
#      filter:
#        slf4j:
#          enabled: true
#          statement-prepare-after-log-enabled: false
#          statement-close-after-log-enabled: false

mybatis-plus:
  type-aliases-package: com.zhou.bms2.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
